HK_CORRELATION_BLOOD_PRESSURE = "HKCorrelationTypeIdentifierBloodPressure"
HK_CORRELATION_FOOD = "HKCorrelationTypeIdentifierFood"

BLOOD_PRESSURE = "Blood Pressure"
FOOD = "Food"

CORRELATIONS = {
    HK_CORRELATION_BLOOD_PRESSURE: BLOOD_PRESSURE,
    HK_CORRELATION_FOOD: FOOD
}
