HK_AVERAGE_METS = "HKAverageMETs"
HK_ELEVATION_ASCENDED = "HKElevationAscended"
HK_INDOOR_WORKOUT = "HKIndoorWorkout"
HK_TIME_ZONE = "HKTimeZone"
HK_WEATHER_HUMIDITY = "HKWeatherHumidity"
HK_WEATHER_TEMPERATURE = "HKWeatherTemperature"
HK_WORKOUT_BRAND_NAME = "HKWorkoutBrandName"
HK_FOOD_MEAL = "HKFoodMeal"
HK_FOOD_TYPE = "HKFoodType"
HK_METADATA_KEY_HEART_RATE_MOTION_CONTEXT = "HKMetadataKeyHeartRateMotionContext"

AVERAGE_METS = "Average METs"
ELEVATION_ASCENDED = "Elevation Ascended"
INDOOR_WORKOUT = "Indoor Workout"
TIME_ZONE = "Time Zone"
WEATHER_HUMIDITY = "Weather Humidity"
WEATHER_TEMPERATURE = "Weather Temperature"
WORKOUT_BRAND_NAME = "Workout Brand Name"
FOOD_MEAL = "Meal"
FOOD_TYPE = "Food Type"
HEART_RATE_MOTION_CONTEXT = "Heart Rate Motion Context"

METADATA = {
    HK_METADATA_KEY_HEART_RATE_MOTION_CONTEXT: HEART_RATE_MOTION_CONTEXT,
    HK_AVERAGE_METS: AVERAGE_METS,
    HK_ELEVATION_ASCENDED: ELEVATION_ASCENDED,
    HK_INDOOR_WORKOUT: INDOOR_WORKOUT,
    HK_TIME_ZONE: TIME_ZONE,
    HK_WEATHER_HUMIDITY: WEATHER_HUMIDITY,
    HK_WEATHER_TEMPERATURE: WEATHER_TEMPERATURE,
    HK_WORKOUT_BRAND_NAME: WORKOUT_BRAND_NAME,
    HK_FOOD_MEAL: FOOD_MEAL,
    HK_FOOD_TYPE: FOOD_TYPE,
}
