HK_RECORD_ACTIVE_ENERGY_BURNED = "HKQuantityTypeIdentifierActiveEnergyBurned"
HK_RECORD_APPLE_EXERCISE_TIME = "HKQuantityTypeIdentifierAppleExerciseTime"
HK_RECORD_APPLE_STAND_HOUR = "HKCategoryTypeIdentifierAppleStandHour"
HK_RECORD_APPLE_STAND_HOUR_IDLE = "HKCategoryValueAppleStandHourIdle"
HK_RECORD_APPLE_STAND_HOUR_STOOD = "HKCategoryValueAppleStandHourStood"
HK_RECORD_APPLE_STAND_TIME = "HKQuantityTypeIdentifierAppleStandTime"
HK_RECORD_AUDIO_EXPOSURE_EVENT_LOUD_ENVIRONMENT = "HKCategoryValueAudioExposureEventLoudEnvironment"
HK_RECORD_BASAL_BODY_TEMPERATURE = "HKQuantityTypeIdentifierBasalBodyTemperature"
HK_RECORD_BASAL_ENERGY_BURNED = "HKQuantityTypeIdentifierBasalEnergyBurned"
HK_RECORD_BLOOD_ALCOHOL_CONTENT = "HKQuantityTypeIdentifierBloodAlcoholContent"
HK_RECORD_BLOOD_GLUCOSE = "HKQuantityTypeIdentifierBloodGlucose"
HK_RECORD_BLOOD_PRESSURE_DIASTOLIC = "HKQuantityTypeIdentifierBloodPressureDiastolic"
HK_RECORD_BLOOD_PRESSURE_SYSTOLIC = "HKQuantityTypeIdentifierBloodPressureSystolic"
HK_RECORD_BODY_FAT_PERCENTAGE = "HKQuantityTypeIdentifierBodyFatPercentage"
HK_RECORD_BODY_MASS = "HKQuantityTypeIdentifierBodyMass"
HK_RECORD_BODY_MASS_INDEX = "HKQuantityTypeIdentifierBodyMassIndex"
HK_RECORD_BODY_TEMPERATURE = "HKQuantityTypeIdentifierBodyTemperature"
HK_RECORD_CERVICAL_MUCUS_QUALITY_CREAMY = "HKCategoryValueCervicalMucusQualityCreamy"
HK_RECORD_CERVICAL_MUCUS_QUALITY_DRY = "HKCategoryValueCervicalMucusQualityDry"
HK_RECORD_CERVICAL_MUCUS_QUALITY_EGG_WHITE = "HKCategoryValueCervicalMucusQualityEggWhite"
HK_RECORD_CERVICAL_MUCUS_QUALITY_STICKY = "HKCategoryValueCervicalMucusQualitySticky"
HK_RECORD_CERVICAL_MUCUS_QUALITY_WATERY = "HKCategoryValueCervicalMucusQualityWatery"
HK_RECORD_DIETARY_BIOTIN = "HKQuantityTypeIdentifierDietaryBiotin"
HK_RECORD_DIETARY_CAFFEINE = "HKQuantityTypeIdentifierDietaryCaffeine"
HK_RECORD_DIETARY_CALCIUM = "HKQuantityTypeIdentifierDietaryCalcium"
HK_RECORD_DIETARY_CARBOHYDRATES = "HKQuantityTypeIdentifierDietaryCarbohydrates"
HK_RECORD_DIETARY_CHLORIDE = "HKQuantityTypeIdentifierDietaryChloride"
HK_RECORD_DIETARY_CHOLESTEROL = "HKQuantityTypeIdentifierDietaryCholesterol"
HK_RECORD_DIETARY_CHROMIUM = "HKQuantityTypeIdentifierDietaryChromium"
HK_RECORD_DIETARY_COPPER = "HKQuantityTypeIdentifierDietaryCopper"
HK_RECORD_DIETARY_ENERGY_CONSUMED = "HKQuantityTypeIdentifierDietaryEnergyConsumed"
HK_RECORD_DIETARY_FAT_MONOUNSATURATED = "HKQuantityTypeIdentifierDietaryFatMonounsaturated"
HK_RECORD_DIETARY_FAT_POLYUNSATURATED = "HKQuantityTypeIdentifierDietaryFatPolyunsaturated"
HK_RECORD_DIETARY_FAT_SATURATED = "HKQuantityTypeIdentifierDietaryFatSaturated"
HK_RECORD_DIETARY_FAT_TOTAL = "HKQuantityTypeIdentifierDietaryFatTotal"
HK_RECORD_DIETARY_FIBER = "HKQuantityTypeIdentifierDietaryFiber"
HK_RECORD_DIETARY_FOLATE = "HKQuantityTypeIdentifierDietaryFolate"
HK_RECORD_DIETARY_IODINE = "HKQuantityTypeIdentifierDietaryIodine"
HK_RECORD_DIETARY_IRON = "HKQuantityTypeIdentifierDietaryIron"
HK_RECORD_DIETARY_MAGNESIUM = "HKQuantityTypeIdentifierDietaryMagnesium"
HK_RECORD_DIETARY_MANGANESE = "HKQuantityTypeIdentifierDietaryManganese"
HK_RECORD_DIETARY_MOLYBDENUM = "HKQuantityTypeIdentifierDietaryMolybdenum"
HK_RECORD_DIETARY_NIACIN = "HKQuantityTypeIdentifierDietaryNiacin"
HK_RECORD_DIETARY_PANTOTHENIC_ACID = "HKQuantityTypeIdentifierDietaryPantothenicAcid"
HK_RECORD_DIETARY_PHOSPHORUS = "HKQuantityTypeIdentifierDietaryPhosphorus"
HK_RECORD_DIETARY_POTASSIUM = "HKQuantityTypeIdentifierDietaryPotassium"
HK_RECORD_DIETARY_PROTEIN = "HKQuantityTypeIdentifierDietaryProtein"
HK_RECORD_DIETARY_RIBOFLAVIN = "HKQuantityTypeIdentifierDietaryRiboflavin"
HK_RECORD_DIETARY_SELENIUM = "HKQuantityTypeIdentifierDietarySelenium"
HK_RECORD_DIETARY_SODIUM = "HKQuantityTypeIdentifierDietarySodium"
HK_RECORD_DIETARY_SUGAR = "HKQuantityTypeIdentifierDietarySugar"
HK_RECORD_DIETARY_THIAMIN = "HKQuantityTypeIdentifierDietaryThiamin"
HK_RECORD_DIETARY_VITAMIN_A = "HKQuantityTypeIdentifierDietaryVitaminA"
HK_RECORD_DIETARY_VITAMIN_B12 = "HKQuantityTypeIdentifierDietaryVitaminB12"
HK_RECORD_DIETARY_VITAMIN_B6 = "HKQuantityTypeIdentifierDietaryVitaminB6"
HK_RECORD_DIETARY_VITAMIN_C = "HKQuantityTypeIdentifierDietaryVitaminC"
HK_RECORD_DIETARY_VITAMIN_D = "HKQuantityTypeIdentifierDietaryVitaminD"
HK_RECORD_DIETARY_VITAMIN_E = "HKQuantityTypeIdentifierDietaryVitaminE"
HK_RECORD_DIETARY_VITAMIN_K = "HKQuantityTypeIdentifierDietaryVitaminK"
HK_RECORD_DIETARY_WATER = "HKQuantityTypeIdentifierDietaryWater"
HK_RECORD_DIETARY_ZINC = "HKQuantityTypeIdentifierDietaryZinc"
HK_RECORD_DISTANCE_CYCLING = "HKQuantityTypeIdentifierDistanceCycling"
HK_RECORD_DISTANCE_DOWNHILL_SNOW_SPORTS = "HKQuantityTypeIdentifierDistanceDownhillSnowSports"
HK_RECORD_DISTANCE_SWIMMING = "HKQuantityTypeIdentifierDistanceSwimming"
HK_RECORD_DISTANCE_WALKING_RUNNING = "HKQuantityTypeIdentifierDistanceWalkingRunning"
HK_RECORD_DISTANCE_WHEELCHAIR = "HKQuantityTypeIdentifierDistanceWheelchair"
HK_RECORD_ELECTRODERMAL_ACTIVITY = "HKQuantityTypeIdentifierElectrodermalActivity"
HK_RECORD_ENVIRONMENTAL_AUDIO_EXPOSURE = "HKQuantityTypeIdentifierEnvironmentalAudioExposure"
HK_RECORD_FLIGHTS_CLIMBED = "HKQuantityTypeIdentifierFlightsClimbed"
HK_RECORD_FORCED_EXPIRATORY_VOLUME1 = "HKQuantityTypeIdentifierForcedExpiratoryVolume1"
HK_RECORD_FORCED_VITAL_CAPACITY = "HKQuantityTypeIdentifierForcedVitalCapacity"
HK_RECORD_HEADPHONE_AUDIO_EXPOSURE = "HKQuantityTypeIdentifierHeadphoneAudioExposure"
HK_RECORD_HEART_RATE = "HKQuantityTypeIdentifierHeartRate"
HK_RECORD_HEART_RATE_VARIABILITY_S_D_N_N = "HKQuantityTypeIdentifierHeartRateVariabilitySDNN"
HK_RECORD_HEIGHT = "HKQuantityTypeIdentifierHeight"
HK_RECORD_INHALER_USAGE = "HKQuantityTypeIdentifierInhalerUsage"
HK_RECORD_INSULIN_DELIVERY = "HKQuantityTypeIdentifierInsulinDelivery"
HK_RECORD_LEAN_BODY_MASS = "HKQuantityTypeIdentifierLeanBodyMass"
HK_RECORD_MINDFUL_SESSION = "HKCategoryTypeIdentifierMindfulSession"
HK_RECORD_NIKE_FUEL = "HKQuantityTypeIdentifierNikeFuel"
HK_RECORD_NOT_APPLICABLE = "HKCategoryValueNotApplicable"
HK_RECORD_NUMBER_OF_TIMES_FALLEN = "HKQuantityTypeIdentifierNumberOfTimesFallen"
HK_RECORD_OVULATION_TEST_RESULT_ESTROGEN_SURGE = "HKCategoryValueOvulationTestResultEstrogenSurge"
HK_RECORD_OVULATION_TEST_RESULT_INDETERMINATE = "HKCategoryValueOvulationTestResultIndeterminate"
HK_RECORD_OVULATION_TEST_RESULT_LUTEINIZING_HORMONE_SURGE = "HKCategoryValueOvulationTestResultLuteinizingHormoneSurge"
HK_RECORD_OVULATION_TEST_RESULT_NEGATIVE = "HKCategoryValueOvulationTestResultNegative"
HK_RECORD_OXYGEN_SATURATION = "HKQuantityTypeIdentifierOxygenSaturation"
HK_RECORD_PEAK_EXPIRATORY_FLOW_RATE = "HKQuantityTypeIdentifierPeakExpiratoryFlowRate"
HK_RECORD_PERIPHERAL_PERFUSION_INDEX = "HKQuantityTypeIdentifierPeripheralPerfusionIndex"
HK_RECORD_PUSH_COUNT = "HKQuantityTypeIdentifierPushCount"
HK_RECORD_RESPIRATORY_RATE = "HKQuantityTypeIdentifierRespiratoryRate"
HK_RECORD_RESTING_HEART_RATE = "HKQuantityTypeIdentifierRestingHeartRate"
HK_RECORD_SLEEP_ANALYSIS = "HKCategoryTypeIdentifierSleepAnalysis"
HK_RECORD_SLEEP_ANALYSIS_ASLEEP = "HKCategoryValueSleepAnalysisAsleep"
HK_RECORD_SLEEP_ANALYSIS_AWAKE = "HKCategoryValueSleepAnalysisAwake"
HK_RECORD_SLEEP_ANALYSIS_IN_BED = "HKCategoryValueSleepAnalysisInBed"
HK_RECORD_STEP_COUNT = "HKQuantityTypeIdentifierStepCount"
HK_RECORD_SWIMMING_STROKE_COUNT = "HKQuantityTypeIdentifierSwimmingStrokeCount"
HK_RECORD_TOOTHBRUSHING_EVENT = "HKCategoryTypeIdentifierToothbrushingEvent"
HK_RECORD_U_V_EXPOSURE = "HKQuantityTypeIdentifierUVExposure"
HK_RECORD_V_O2_MAX = "HKQuantityTypeIdentifierVO2Max"
HK_RECORD_WAIST_CIRCUMFERENCE = "HKQuantityTypeIdentifierWaistCircumference"
HK_RECORD_WALKING_HEART_RATE_AVERAGE = "HKQuantityTypeIdentifierWalkingHeartRateAverage"

ACTIVE_ENERGY_BURNED = "Active Energy Burned"
BASAL_BODY_TEMPERATURE = "Basal Body Temperature"
BASAL_ENERGY_BURNED = "Basal Energy Burned"
BIOTIN = "Biotin"
BLOOD_ALCOHOL_CONTENT = "Blood Alcohol Content"
BLOOD_GLUCOSE = "Blood Glucose"
BLOOD_PRESSURE_DIASTOLIC = "Blood Pressure Diastolic"
BLOOD_PRESSURE_SYSTOLIC = "Blood Pressure Systolic"
BODY_FAT_PERCENTAGE = "Body Fat Percentage"
BODY_MASS = "Body Mass"
BODY_MASS_INDEX = "Body Mass Index"
BODY_TEMPERATURE = "Body Temperature"
CAFFEINE = "Caffeine"
CALCIUM = "Calcium"
CARBOHYDRATES = "Carbohydrates"
CHLORIDE = "Chloride"
CHOLESTEROL = "Cholesterol"
CHROMIUM = "Chromium"
COPPER = "Copper"
DISTANCE_CYCLING = "Distance Cycling"
DISTANCE_DOWNHILL_SNOW_SPORTS = "Distance Downhill Snow Sports"
DISTANCE_SWIMMING = "Distance Swimming"
DISTANCE_WALKING_RUNNING = "Distance Walking/Running"
DISTANCE_WHEELCHAIR = "Distance Wheelchair"
ELECTRODERMAL_ACTIVITY = "Electrodermal Activity"
ENERGY_CONSUMED = "Energy Consumed"
ENVIRONMENTAL_AUDIO_EXPOSURE = "Environmental Audio Exposure"
EXERCISE_TIME = "Exercise Time"
FAT_MONOUNSATURATED = "Fat Monounsaturated"
FAT_POLYUNSATURATED = "Fat Polyunsaturated"
FAT_SATURATED = "Fat Saturated"
FAT_TOTAL = "Fat Total"
FIBER = "Fiber"
FLIGHTS_CLIMBED = "Flights Climbed"
FOLATE = "Folate"
FORCED_EXPIRATORY_VOLUME1 = "Forced Expiratory Volume1"
FORCED_VITAL_CAPACITY = "Forced Vital Capacity"
HEADPHONE_AUDIO_EXPOSURE = "Headphone Audio Exposure"
HEART_RATE = "Heart Rate"
HEART_RATE_VARIABILITY = "Heart Rate Variability"
HEIGHT = "Height"
INHALER_USAGE = "Inhaler Usage"
INSULIN_DELIVERY = "Insulin Delivery"
IODINE = "Iodine"
IRON = "Iron"
LEAN_BODY_MASS = "Lean Body Mass"
MAGNESIUM = "Magnesium"
MANGANESE = "Manganese"
MINDFUL_SESSION = "Mindful Session"
MOLYBDENUM = "Molybdenum"
NIACIN = "Niacin"
NIKE_FUEL = "Nike Fuel"
NUMBER_OF_TIMES_FALLEN = "Number Of Times Fallen"
OXYGEN_SATURATION = "Oxygen Saturation"
PANTOTHENIC_ACID = "Pantothenic Acid"
PEAK_EXPIRATORY_FLOW_RATE = "Peak Expiratory Flow Rate"
PERIPHERAL_PERFUSION_INDEX = "Peripheral Perfusion Index"
PHOSPHORUS = "Phosphorus"
POTASSIUM = "Potassium"
PROTEIN = "Protein"
PUSH_COUNT = "Push Count"
RESPIRATORY_RATE = "Respiratory Rate"
RESTING_HEART_RATE = "Resting Heart Rate"
RIBOFLAVIN = "Riboflavin"
SELENIUM = "Selenium"
SLEEP_ANALYSIS = "Sleep Analysis"
SODIUM = "Sodium"
STAND_HOUR = "Stand Hour"
STAND_TIME = "Stand Time"
STEP_COUNT = "Step Count"
SUGAR = "Sugar"
SWIMMING_STROKE_COUNT = "Swimming Stroke Count"
THIAMIN = "Thiamin"
TOOTHBRUSHING_EVENT = "Toothbrushing Event"
U_V_EXPOSURE = "U V Exposure"
V_O2_MAX = "V O2 Max"
VITAMIN_A = "Vitamin A"
VITAMIN_B12 = "Vitamin B12"
VITAMIN_B6 = "Vitamin B6"
VITAMIN_C = "Vitamin C"
VITAMIN_D = "Vitamin D"
VITAMIN_E = "Vitamin E"
VITAMIN_K = "Vitamin K"
WAIST_CIRCUMFERENCE = "Waist Circumference"
WALKING_HEART_RATE_AVERAGE = "Walking Heart Rate Average"
WATER = "Water"
ZINC = "Zinc"


RECORDS = {
    HK_RECORD_APPLE_STAND_HOUR: STAND_HOUR,
    HK_RECORD_MINDFUL_SESSION: MINDFUL_SESSION,
    HK_RECORD_SLEEP_ANALYSIS: SLEEP_ANALYSIS,
    HK_RECORD_TOOTHBRUSHING_EVENT: TOOTHBRUSHING_EVENT,
    HK_RECORD_ACTIVE_ENERGY_BURNED: ACTIVE_ENERGY_BURNED,
    HK_RECORD_APPLE_EXERCISE_TIME: EXERCISE_TIME,
    HK_RECORD_APPLE_STAND_TIME: STAND_TIME,
    HK_RECORD_BASAL_BODY_TEMPERATURE: BASAL_BODY_TEMPERATURE,
    HK_RECORD_BASAL_ENERGY_BURNED: BASAL_ENERGY_BURNED,
    HK_RECORD_BLOOD_ALCOHOL_CONTENT: BLOOD_ALCOHOL_CONTENT,
    HK_RECORD_BLOOD_GLUCOSE: BLOOD_GLUCOSE,
    HK_RECORD_BLOOD_PRESSURE_DIASTOLIC: BLOOD_PRESSURE_DIASTOLIC,
    HK_RECORD_BLOOD_PRESSURE_SYSTOLIC: BLOOD_PRESSURE_SYSTOLIC,
    HK_RECORD_BODY_FAT_PERCENTAGE: BODY_FAT_PERCENTAGE,
    HK_RECORD_BODY_MASS: BODY_MASS,
    HK_RECORD_BODY_MASS_INDEX: BODY_MASS_INDEX,
    HK_RECORD_BODY_TEMPERATURE: BODY_TEMPERATURE,
    HK_RECORD_DIETARY_BIOTIN: BIOTIN,
    HK_RECORD_DIETARY_CAFFEINE: CAFFEINE,
    HK_RECORD_DIETARY_CALCIUM: CALCIUM,
    HK_RECORD_DIETARY_CARBOHYDRATES: CARBOHYDRATES,
    HK_RECORD_DIETARY_CHLORIDE: CHLORIDE,
    HK_RECORD_DIETARY_CHOLESTEROL: CHOLESTEROL,
    HK_RECORD_DIETARY_CHROMIUM: CHROMIUM,
    HK_RECORD_DIETARY_COPPER: COPPER,
    HK_RECORD_DIETARY_ENERGY_CONSUMED: ENERGY_CONSUMED,
    HK_RECORD_DIETARY_FAT_MONOUNSATURATED: FAT_MONOUNSATURATED,
    HK_RECORD_DIETARY_FAT_POLYUNSATURATED: FAT_POLYUNSATURATED,
    HK_RECORD_DIETARY_FAT_SATURATED: FAT_SATURATED,
    HK_RECORD_DIETARY_FAT_TOTAL: FAT_TOTAL,
    HK_RECORD_DIETARY_FIBER: FIBER,
    HK_RECORD_DIETARY_FOLATE: FOLATE,
    HK_RECORD_DIETARY_IODINE: IODINE,
    HK_RECORD_DIETARY_IRON: IRON,
    HK_RECORD_DIETARY_MAGNESIUM: MAGNESIUM,
    HK_RECORD_DIETARY_MANGANESE: MANGANESE,
    HK_RECORD_DIETARY_MOLYBDENUM: MOLYBDENUM,
    HK_RECORD_DIETARY_NIACIN: NIACIN,
    HK_RECORD_DIETARY_PANTOTHENIC_ACID: PANTOTHENIC_ACID,
    HK_RECORD_DIETARY_PHOSPHORUS: PHOSPHORUS,
    HK_RECORD_DIETARY_POTASSIUM: POTASSIUM,
    HK_RECORD_DIETARY_PROTEIN: PROTEIN,
    HK_RECORD_DIETARY_RIBOFLAVIN: RIBOFLAVIN,
    HK_RECORD_DIETARY_SELENIUM: SELENIUM,
    HK_RECORD_DIETARY_SODIUM: SODIUM,
    HK_RECORD_DIETARY_SUGAR: SUGAR,
    HK_RECORD_DIETARY_THIAMIN: THIAMIN,
    HK_RECORD_DIETARY_VITAMIN_A: VITAMIN_A,
    HK_RECORD_DIETARY_VITAMIN_B12: VITAMIN_B12,
    HK_RECORD_DIETARY_VITAMIN_B6: VITAMIN_B6,
    HK_RECORD_DIETARY_VITAMIN_C: VITAMIN_C,
    HK_RECORD_DIETARY_VITAMIN_D: VITAMIN_D,
    HK_RECORD_DIETARY_VITAMIN_E: VITAMIN_E,
    HK_RECORD_DIETARY_VITAMIN_K: VITAMIN_K,
    HK_RECORD_DIETARY_WATER: WATER,
    HK_RECORD_DIETARY_ZINC: ZINC,
    HK_RECORD_DISTANCE_CYCLING: DISTANCE_CYCLING,
    HK_RECORD_DISTANCE_DOWNHILL_SNOW_SPORTS: DISTANCE_DOWNHILL_SNOW_SPORTS,
    HK_RECORD_DISTANCE_SWIMMING: DISTANCE_SWIMMING,
    HK_RECORD_DISTANCE_WALKING_RUNNING: DISTANCE_WALKING_RUNNING,
    HK_RECORD_DISTANCE_WHEELCHAIR: DISTANCE_WHEELCHAIR,
    HK_RECORD_ELECTRODERMAL_ACTIVITY: ELECTRODERMAL_ACTIVITY,
    HK_RECORD_ENVIRONMENTAL_AUDIO_EXPOSURE: ENVIRONMENTAL_AUDIO_EXPOSURE,
    HK_RECORD_FLIGHTS_CLIMBED: FLIGHTS_CLIMBED,
    HK_RECORD_FORCED_EXPIRATORY_VOLUME1: FORCED_EXPIRATORY_VOLUME1,
    HK_RECORD_FORCED_VITAL_CAPACITY: FORCED_VITAL_CAPACITY,
    HK_RECORD_HEADPHONE_AUDIO_EXPOSURE: HEADPHONE_AUDIO_EXPOSURE,
    HK_RECORD_HEART_RATE: HEART_RATE,
    HK_RECORD_HEART_RATE_VARIABILITY_S_D_N_N: HEART_RATE_VARIABILITY,
    HK_RECORD_HEIGHT: HEIGHT,
    HK_RECORD_INHALER_USAGE: INHALER_USAGE,
    HK_RECORD_INSULIN_DELIVERY: INSULIN_DELIVERY,
    HK_RECORD_LEAN_BODY_MASS: LEAN_BODY_MASS,
    HK_RECORD_NIKE_FUEL: NIKE_FUEL,
    HK_RECORD_NUMBER_OF_TIMES_FALLEN: NUMBER_OF_TIMES_FALLEN,
    HK_RECORD_OXYGEN_SATURATION: OXYGEN_SATURATION,
    HK_RECORD_PEAK_EXPIRATORY_FLOW_RATE: PEAK_EXPIRATORY_FLOW_RATE,
    HK_RECORD_PERIPHERAL_PERFUSION_INDEX: PERIPHERAL_PERFUSION_INDEX,
    HK_RECORD_PUSH_COUNT: PUSH_COUNT,
    HK_RECORD_RESPIRATORY_RATE: RESPIRATORY_RATE,
    HK_RECORD_RESTING_HEART_RATE: RESTING_HEART_RATE,
    HK_RECORD_STEP_COUNT: STEP_COUNT,
    HK_RECORD_SWIMMING_STROKE_COUNT: SWIMMING_STROKE_COUNT,
    HK_RECORD_U_V_EXPOSURE: U_V_EXPOSURE,
    HK_RECORD_V_O2_MAX: V_O2_MAX,
    HK_RECORD_WAIST_CIRCUMFERENCE: WAIST_CIRCUMFERENCE,
    HK_RECORD_WALKING_HEART_RATE_AVERAGE: WALKING_HEART_RATE_AVERAGE,
}
