HK_WORKOUT_AMERICAN_FOOTBALL = "HKWorkoutActivityTypeAmericanFootball"
HK_WORKOUT_ARCHERY = "HKWorkoutActivityTypeArchery"
HK_WORKOUT_AUSTRALIAN_FOOTBALL = "HKWorkoutActivityTypeAustralianFootball"
HK_WORKOUT_BADMINTON = "HKWorkoutActivityTypeBadminton"
HK_WORKOUT_BASEBALL = "HKWorkoutActivityTypeBaseball"
HK_WORKOUT_BASKETBALL = "HKWorkoutActivityTypeBasketball"
HK_WORKOUT_BOWLING = "HKWorkoutActivityTypeBowling"
HK_WORKOUT_BOXING = "HKWorkoutActivityTypeBoxing"
HK_WORKOUT_CLIMBING = "HKWorkoutActivityTypeClimbing"
HK_WORKOUT_CRICKET = "HKWorkoutActivityTypeCricket"
HK_WORKOUT_CROSS_TRAINING = "HKWorkoutActivityTypeCrossTraining"
HK_WORKOUT_CURLING = "HKWorkoutActivityTypeCurling"
HK_WORKOUT_CYCLING = "HKWorkoutActivityTypeCycling"
HK_WORKOUT_DANCE = "HKWorkoutActivityTypeDance"
HK_WORKOUT_DANCE_INSPIRED_TRAINING = "HKWorkoutActivityTypeDanceInspiredTraining"
HK_WORKOUT_ELLIPTICAL = "HKWorkoutActivityTypeElliptical"
HK_WORKOUT_EQUESTRIAN_SPORTS = "HKWorkoutActivityTypeEquestrianSports"
HK_WORKOUT_FENCING = "HKWorkoutActivityTypeFencing"
HK_WORKOUT_FISHING = "HKWorkoutActivityTypeFishing"
HK_WORKOUT_FUNCTIONAL_STRENGTH_TRAINING = "HKWorkoutActivityTypeFunctionalStrengthTraining"
HK_WORKOUT_GOLF = "HKWorkoutActivityTypeGolf"
HK_WORKOUT_GYMNASTICS = "HKWorkoutActivityTypeGymnastics"
HK_WORKOUT_HANDBALL = "HKWorkoutActivityTypeHandball"
HK_WORKOUT_HIGH_INTENSITY_INTERVAL_TRAINING = "HKWorkoutActivityTypeHighIntensityIntervalTraining"
HK_WORKOUT_HIKING = "HKWorkoutActivityTypeHiking"
HK_WORKOUT_HOCKEY = "HKWorkoutActivityTypeHockey"
HK_WORKOUT_HUNTING = "HKWorkoutActivityTypeHunting"
HK_WORKOUT_LACROSSE = "HKWorkoutActivityTypeLacrosse"
HK_WORKOUT_MARTIAL_ARTS = "HKWorkoutActivityTypeMartialArts"
HK_WORKOUT_MIND_AND_BODY = "HKWorkoutActivityTypeMindAndBody"
HK_WORKOUT_MIXED_METABOLIC_CARDIO_TRAINING = "HKWorkoutActivityTypeMixedMetabolicCardioTraining"
HK_WORKOUT_OTHER = "HKWorkoutActivityTypeOther"
HK_WORKOUT_PADDLE_SPORTS = "HKWorkoutActivityTypePaddleSports"
HK_WORKOUT_PLAY = "HKWorkoutActivityTypePlay"
HK_WORKOUT_PREPARATION_AND_RECOVERY = "HKWorkoutActivityTypePreparationAndRecovery"
HK_WORKOUT_RACQUETBALL = "HKWorkoutActivityTypeRacquetball"
HK_WORKOUT_ROWING = "HKWorkoutActivityTypeRowing"
HK_WORKOUT_RUGBY = "HKWorkoutActivityTypeRugby"
HK_WORKOUT_RUNNING = "HKWorkoutActivityTypeRunning"
HK_WORKOUT_SAILING = "HKWorkoutActivityTypeSailing"
HK_WORKOUT_SKATING_SPORTS = "HKWorkoutActivityTypeSkatingSports"
HK_WORKOUT_SNOW_SPORTS = "HKWorkoutActivityTypeSnowSports"
HK_WORKOUT_SOCCER = "HKWorkoutActivityTypeSoccer"
HK_WORKOUT_SOFTBALL = "HKWorkoutActivityTypeSoftball"
HK_WORKOUT_SQUASH = "HKWorkoutActivityTypeSquash"
HK_WORKOUT_STAIR_CLIMBING = "HKWorkoutActivityTypeStairClimbing"
HK_WORKOUT_SURFING_SPORTS = "HKWorkoutActivityTypeSurfingSports"
HK_WORKOUT_SWIMMING = "HKWorkoutActivityTypeSwimming"
HK_WORKOUT_TABLE_TENNIS = "HKWorkoutActivityTypeTableTennis"
HK_WORKOUT_TENNIS = "HKWorkoutActivityTypeTennis"
HK_WORKOUT_TRACK_AND_FIELD = "HKWorkoutActivityTypeTrackAndField"
HK_WORKOUT_TRADITIONAL_STRENGTH_TRAINING = "HKWorkoutActivityTypeTraditionalStrengthTraining"
HK_WORKOUT_VOLLEYBALL = "HKWorkoutActivityTypeVolleyball"
HK_WORKOUT_WALKING = "HKWorkoutActivityTypeWalking"
HK_WORKOUT_WATER_FITNESS = "HKWorkoutActivityTypeWaterFitness"
HK_WORKOUT_WATER_POLO = "HKWorkoutActivityTypeWaterPolo"
HK_WORKOUT_WATER_SPORTS = "HKWorkoutActivityTypeWaterSports"
HK_WORKOUT_WRESTLING = "HKWorkoutActivityTypeWrestling"
HK_WORKOUT_YOGA = "HKWorkoutActivityTypeYoga"

AMERICAN_FOOTBALL = "American Football"
ARCHERY = "Archery"
AUSTRALIAN_FOOTBALL = "Australian Football"
BADMINTON = "Badminton"
BASEBALL = "Baseball"
BASKETBALL = "Basketball"
BOWLING = "Bowling"
BOXING = "Boxing"
CLIMBING = "Climbing"
CRICKET = "Cricket"
CROSS_TRAINING = "Cross Training"
CURLING = "Curling"
CYCLING = "Cycling"
DANCE = "Dance"
DANCE_INSPIRED_TRAINING = "Dance Inspired Training"
ELLIPTICAL = "Elliptical"
EQUESTRIAN_SPORTS = "Equestrian Sports"
FENCING = "Fencing"
FISHING = "Fishing"
FUNCTIONAL_STRENGTH_TRAINING = "Functional Strength Training"
GOLF = "Golf"
GYMNASTICS = "Gymnastics"
HANDBALL = "Handball"
HIGH_INTENSITY_INTERVAL_TRAINING = "High Intensity Interval Training"
HIKING = "Hiking"
HOCKEY = "Hockey"
HUNTING = "Hunting"
LACROSSE = "Lacrosse"
MARTIAL_ARTS = "Martial Arts"
MIND_AND_BODY = "Mind And Body"
MIXED_METABOLIC_CARDIO_TRAINING = "Mixed Metabolic Cardio Training"
OTHER = "Other"
PADDLE_SPORTS = "Paddle Sports"
PLAY = "Play"
PREPARATION_AND_RECOVERY = "Preparation And Recovery"
RACQUETBALL = "Racquetball"
ROWING = "Rowing"
RUGBY = "Rugby"
RUNNING = "Running"
SAILING = "Sailing"
SKATING_SPORTS = "Skating Sports"
SNOW_SPORTS = "Snow Sports"
SOCCER = "Soccer"
SOFTBALL = "Softball"
SQUASH = "Squash"
STAIR_CLIMBING = "Stair Climbing"
SURFING_SPORTS = "Surfing Sports"
SWIMMING = "Swimming"
TABLE_TENNIS = "Table Tennis"
TENNIS = "Tennis"
TRACK_AND_FIELD = "Track And Field"
TRADITIONAL_STRENGTH_TRAINING = "Traditional Strength Training"
VOLLEYBALL = "Volleyball"
WALKING = "Walking"
WATER_FITNESS = "Water Fitness"
WATER_POLO = "Water Polo"
WATER_SPORTS = "Water Sports"
WRESTLING = "Wrestling"
YOGA = "Yoga"


WORKOUTS = {
    HK_WORKOUT_AMERICAN_FOOTBALL: AMERICAN_FOOTBALL,
    HK_WORKOUT_ARCHERY: ARCHERY,
    HK_WORKOUT_AUSTRALIAN_FOOTBALL: AUSTRALIAN_FOOTBALL,
    HK_WORKOUT_BADMINTON: BADMINTON,
    HK_WORKOUT_BASEBALL: BASEBALL,
    HK_WORKOUT_BASKETBALL: BASKETBALL,
    HK_WORKOUT_BOWLING: BOWLING,
    HK_WORKOUT_BOXING: BOXING,
    HK_WORKOUT_CLIMBING: CLIMBING,
    HK_WORKOUT_CRICKET: CRICKET,
    HK_WORKOUT_CROSS_TRAINING: CROSS_TRAINING,
    HK_WORKOUT_CURLING: CURLING,
    HK_WORKOUT_CYCLING: CYCLING,
    HK_WORKOUT_DANCE: DANCE,
    HK_WORKOUT_DANCE_INSPIRED_TRAINING: DANCE_INSPIRED_TRAINING,
    HK_WORKOUT_ELLIPTICAL: ELLIPTICAL,
    HK_WORKOUT_EQUESTRIAN_SPORTS: EQUESTRIAN_SPORTS,
    HK_WORKOUT_FENCING: FENCING,
    HK_WORKOUT_FISHING: FISHING,
    HK_WORKOUT_FUNCTIONAL_STRENGTH_TRAINING: FUNCTIONAL_STRENGTH_TRAINING,
    HK_WORKOUT_GOLF: GOLF,
    HK_WORKOUT_GYMNASTICS: GYMNASTICS,
    HK_WORKOUT_HANDBALL: HANDBALL,
    HK_WORKOUT_HIGH_INTENSITY_INTERVAL_TRAINING: HIGH_INTENSITY_INTERVAL_TRAINING,
    HK_WORKOUT_HIKING: HIKING,
    HK_WORKOUT_HOCKEY: HOCKEY,
    HK_WORKOUT_HUNTING: HUNTING,
    HK_WORKOUT_LACROSSE: LACROSSE,
    HK_WORKOUT_MARTIAL_ARTS: MARTIAL_ARTS,
    HK_WORKOUT_MIND_AND_BODY: MIND_AND_BODY,
    HK_WORKOUT_MIXED_METABOLIC_CARDIO_TRAINING: MIXED_METABOLIC_CARDIO_TRAINING,
    HK_WORKOUT_OTHER: OTHER,
    HK_WORKOUT_PADDLE_SPORTS: PADDLE_SPORTS,
    HK_WORKOUT_PLAY: PLAY,
    HK_WORKOUT_PREPARATION_AND_RECOVERY: PREPARATION_AND_RECOVERY,
    HK_WORKOUT_RACQUETBALL: RACQUETBALL,
    HK_WORKOUT_ROWING: ROWING,
    HK_WORKOUT_RUGBY: RUGBY,
    HK_WORKOUT_RUNNING: RUNNING,
    HK_WORKOUT_SAILING: SAILING,
    HK_WORKOUT_SKATING_SPORTS: SKATING_SPORTS,
    HK_WORKOUT_SNOW_SPORTS: SNOW_SPORTS,
    HK_WORKOUT_SOCCER: SOCCER,
    HK_WORKOUT_SOFTBALL: SOFTBALL,
    HK_WORKOUT_SQUASH: SQUASH,
    HK_WORKOUT_STAIR_CLIMBING: STAIR_CLIMBING,
    HK_WORKOUT_SURFING_SPORTS: SURFING_SPORTS,
    HK_WORKOUT_SWIMMING: SWIMMING,
    HK_WORKOUT_TABLE_TENNIS: TABLE_TENNIS,
    HK_WORKOUT_TENNIS: TENNIS,
    HK_WORKOUT_TRACK_AND_FIELD: TRACK_AND_FIELD,
    HK_WORKOUT_TRADITIONAL_STRENGTH_TRAINING: TRADITIONAL_STRENGTH_TRAINING,
    HK_WORKOUT_VOLLEYBALL: VOLLEYBALL,
    HK_WORKOUT_WALKING: WALKING,
    HK_WORKOUT_WATER_FITNESS: WATER_FITNESS,
    HK_WORKOUT_WATER_POLO: WATER_POLO,
    HK_WORKOUT_WATER_SPORTS: WATER_SPORTS,
    HK_WORKOUT_WRESTLING: WRESTLING,
    HK_WORKOUT_YOGA: YOGA,
}
