name: Push to master branch

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Upgrade pip
        run: |
          pip install --upgrade pip

      - name: Install project requirements
        run: |
          pip install -r requirements.txt
          pip install -r requirements-test.txt

      - name: Run tests with coverage
        run: |
          coverage run --source apple_health -m unittest discover
          coverage xml -o ./coverage.xml

      - name: Fix Code Coverage Paths
        run: |
          sed -i "s@${GITHUB_WORKSPACE}@/github/workspace/@g" ./coverage.xml
        
      - name: SonarCloud Scan
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          SONAR_TOKEN: ${{ secrets.TOKEN_SONAR }}
        uses: sonarsource/sonarcloud-github-action@master

  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: test

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools
        pip install wheel

    - name: Build
      run: |
        python setup.py sdist bdist_wheel
