name: Publish Package

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools
        pip install wheel
        pip install twine

    - name: Build
      run: |
        python setup.py sdist bdist_wheel

    - name: Publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TOKEN_PYPI }}
      run: |
        twine upload dist/*

    - name: Notify
      with:
        slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
        pypi_project_name: apple-health
      uses: fedecalendino/slack-release-notifier@v1.1.0
